### ISSUE TITLE
Empty dialog box for language pack selection.

### ISSUE THREAD

**Issue by FredBezies** [obrevenge/revenge_installer#11]
Hello.

It is related to bug #9 in some ways.

Face this bug while testing july 2017 release of Revenge Installer. For both Firefox and Libreoffice, when installer ask me to choose a langpack, I've only an empty dialog box, with a checkbox.

See this screenshot : 

![empty langpack](https://user-images.githubusercontent.com/8571419/27768896-f14902d4-5f1e-11e7-9e3b-0822cc36e940.png)

What's going on?

**Comment by FredBezies** [comment]
Looks like this dialog is not working with both xfce4/xfce4+goodies option or mate/mate+mate extra options in desktop selection dialog box.

I got the option dialog with langpack listed using openbox+tint2 theme option.

**Comment by spookykidmm** [comment]
This is probably just a fluke, should work now

**Comment by FredBezies** [comment]
Half-fixed. Firefox is OK, but LibreOffice is not. At least, there is some progress.

And of course empty line choice = no installation :(

**Comment by spookykidmm** [comment]
Should be fixed

_Sent from my Samsung SAMSUNG-SM-G935A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by FredBezies** [comment]
Fixed indeed.
