### ISSUE TITLE
Neither Firefox or LibreOffice are installed after asking for them.

### ISSUE THREAD

**Issue by FredBezies** [obrevenge/revenge_installer#12]
Simple to reproduce. Ask for both software to be installed. After reboot and login, you won't find them. Annoying :(

**Comment by FredBezies** [comment]
Half fixed. Looks like it is kinda related to translation pack choice in bug #11 

I can now choose a translation pack for firefox and gets it installed. But not for LibreOffice :(

**Comment by spookykidmm** [comment]
Interesting, I'll do some work on it today. I'm glad the keyboard thing is taken care of, though

**Comment by spookykidmm** [comment]
I am super sure it is fixed. Now, at least

**Comment by FredBezies** [comment]
Maybe but I cannot test it right now.

I create a new VBox machine, and right after I click on "yes" to launch installer, it throws me right to last dialog box, the one with chroot option, restart and so on. 

Just look at this video I recorded and stored on my google drive space : https://drive.google.com/open?id=0B7EJYVTtDRj5WmNaY3hWNjFhVTg

Very weird :(

**Comment by spookykidmm** [comment]
Yeah, I forgot to remove an extra parenthese in a place it shouldn't have been. Good to go now

**Comment by FredBezies** [comment]
Another bug bites the dust. Thanks for the fix.
