### ISSUE TITLE
Spooky_aur is listed twice in /etc/pacman.conf

### ISSUE THREAD

**Issue by FredBezies** [obrevenge/revenge_installer#13]
A very simple bug to verify.? Just open /etc/pacman.conf and look at the bottom :(

![spooky](https://user-images.githubusercontent.com/8571419/27768984-a08fcab0-5f20-11e7-95b6-c6c3fb1e6406.png)

**Comment by spookykidmm** [comment]
Yeah this is just the nature of the beast, and I must include both because there is no way to verify if you said yes to one or both, so I just have to go ahead and tell each one to add the lines
