### ISSUE TITLE
QT4 package is not added when choosing VLC in software list.

### ISSUE THREAD

**Issue by FredBezies** [obrevenge/revenge_installer#15]
Hello.

I installed an archlinux with xfce this morning using Revenge Installer and I noticed that QT4 package was not installed when selecting vlc...

Simple bug to fix, I guess?

**Comment by spookykidmm** [comment]
I mean it SHOULD be, but not really. I may just have to include phonon-qt4-vlc in the apps list

**Comment by FredBezies** [comment]
Well, QT4 being in optdepends touched every single automated installer for archlinux... So, you're not alone here !
