### ISSUE TITLE
Guest modules for VirtualBox are not installed in a VirtualBox machine.

### ISSUE THREAD

**Issue by FredBezies** [obrevenge/revenge_installer#18]
An annoying bug I found. When you install Zen Installer in a VirtualBox machine (in order to beta test it for example), virtualbox-guest-modules-arch (or virtualbox-guest-modules-dkms for other kernels than the main one) are not installed.

You have to install them by hand or you won't have a working display with display manager like LightDM.

**Comment by spookykidmm** [comment]
![2017-08-24-045543_1366x768_scrot](https://user-images.githubusercontent.com/10724754/29658379-9dc90940-8888-11e7-869e-0db14949ae49.png)
![2017-08-24-045518_1366x768_scrot](https://user-images.githubusercontent.com/10724754/29658387-a4e7e142-8888-11e7-9cc8-789a86693faa.png)
They're installed by zen and in the default iso. Are you sure they're not installed?

**Comment by FredBezies** [comment]
On first boot on installed system, there is no virtualbox modules. Will try again, doing a screencast to show my steps.

Here is the screencast. Youtube won't index it. I will delete it as soon as you don't need it anymore. Around 12 minutes. Cannot make it shorter :(

https://www.youtube.com/watch?v=GpzJtjnTrmg

No sound, but you can see on a very light installation, on first start, there is no virtualbox modules. After installing them manually, everything works.

**Comment by spookykidmm** [comment]
Should be fixed now

_Sent from my Samsung SAMSUNG-SM-G935A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by FredBezies** [comment]
It is fixed. A good bug is a dead bug :)

Closing issue and removing screencast as it is useless now.
