### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by ghost** [obrevenge/revenge_installer#20]
Heard about this a while ago and spun up a vm, was wondering why there isn't an option for drive encryption?

Cool project though.

**Comment by spookykidmm** [comment]
Hey, please keep up with updates under spookykidmm/zen_installer either here or gitlab. I'll look into drive encryption!

**Comment by ghost** [comment]
:+1:

**Comment by spookykidmm** [comment]
https://computingforgeeks.com/install-arch-linux-luks-encryption/ is this pretty accurate to how drive encryption works?

**Comment by ghost** [comment]
I'm not a giant expert, but I would imagine so, yes.
