### ISSUE TITLE
Keyboard layout selected is not applied during installation.

### ISSUE THREAD

**Issue by FredBezies** [obrevenge/revenge_installer#5]
Hello. 

I'm currently testing revenge installer 0.82.

I noticed that keyboard layout selected it not applied. If I choose an azerty based layout, keys are not mapped correctly in typing inputs, like hostname or password. I press "A" key, it printed "Q" on screen :(

**Comment by spookykidmm** [comment]
Let me know if it works this time around

**Comment by FredBezies** [comment]
Doesn't work. By the way, I noticed a display bug.

After selecting my locale which is fr_FR.UTF-8, fr layout wasn't available in keyboard layout list. See this screenshot : 

![keyboard-choice-fr-01](https://user-images.githubusercontent.com/8571419/27768870-4129c870-5f1e-11e7-8aa8-57bff9effe68.png)

And if I scroll to the bottom of the list, I noticed a blank line with a checkbox.

See this other screenshot : 

![keyboard-choice-fr-02](https://user-images.githubusercontent.com/8571419/27768876-5b0628f6-5f1e-11e7-8d22-9be7b3959dda.png)

**Comment by spookykidmm** [comment]
that's interesting, it looks like the list dialog isn't even picking up the fr layout

**Comment by FredBezies** [comment]
Weird bug indeed :(

**Comment by spookykidmm** [comment]
Did you reboot after applying the new layout?

**Comment by spookykidmm** [comment]
Alright, so do me a quick favor. On your system, run setxkbmap -layout fr -variant ,azerty
And let me know if it works at that point

**Comment by FredBezies** [comment]
It worked. Keyboard was correctly set.

**Comment by spookykidmm** [comment]
Interesting, now run
localectl --no-convert set-x11-keymap " "  ,azerty " "
And reboot and try again

**Comment by FredBezies** [comment]
I also used localectl set-x11-keymap followed by keyboard shortcut. So I know it will work :)

**Comment by spookykidmm** [comment]
This should be perfectly fine now, I just made it so now keyboard layout directly edits the config file

**Comment by FredBezies** [comment]
Just waiting for a new ISO to verify this :D

**Comment by spookykidmm** [comment]
No need for a new ISO, all changes are automatically pulled from this repo

**Comment by FredBezies** [comment]
A good bug is a fixed bug. Next? :)

**Comment by FredBezies** [comment]
Looks like this pita bug is back again :( Ouch !

**Comment by spookykidmm** [comment]
I have no idea why, the installer literally edits the keyboard configuration file. There is no reason it should not be working

**Comment by spookykidmm** [comment]
In the installed system, go to /etc/X11/xorg.conf.d and send me a screenshot of the text file with the word keyboard in it

**Comment by FredBezies** [comment]
Keyboard is not set correctly during installation... In post-install, well, just see this 00-keyboard.conf file.

![virtualbox_revenge installer 0 8 5_07_07_2017_11_13_34](https://user-images.githubusercontent.com/8571419/27951517-85a08c6a-6305-11e7-842b-6670c285a08d.png)

Editing bug summary.

**Comment by spookykidmm** [comment]
Yeah, that's exactly how the file should look

**Comment by spookykidmm** [comment]
So wait, was the file wrong before and you changed it or just rebooted?

**Comment by FredBezies** [comment]
I did not modify it. It was correctly set up by installer.

The problem is keyboard layout - set to french as I asked - was not recognized as the good layout in installation script.

I had to open an xterm and type setxkbmap fr to get the right layout during installation.

**Comment by spookykidmm** [comment]
Alright, give me a step-by-step on exactly what is happening during installation

**Comment by FredBezies** [comment]
Step by step starting on "Hello, I'm revenge installer, welcome!"

1) automatic partitioning selecting which drive to work on.
2) after partitionning, selecting locale
3) on keyboard model, even if I click on "no" to "Would you like to change your keyboard model", a dialog appears.
4) selecting right keyboard model
5) selecting country code for keyboard
6) on keyboard variant, even if I don't want one, a dialog box appears with all availables options.
7) selecting right variant to go on
8) timezone setup with UTC / localtime choice
9) when I arrived to hostname, I noticed pressing "A" key on my azerty keyboard throws me a "Q" in input zone

Hope it helps a little

**Comment by spookykidmm** [comment]
OHHHHH. you're asking for it to be set in the live environment. Yeah, okay, that is super easy to fix 

_Sent from my Samsung SAMSUNG-SM-G935A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by FredBezies** [comment]
I think we nailed it!

I hope to see this bug dead for good soon. Besides this, it is a real pleasure to use your installer.

**Comment by spookykidmm** [comment]
Should be good now

_Sent from my Samsung SAMSUNG-SM-G935A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by FredBezies** [comment]
It is. Sorry for not telling you before. Fixed!
