### ISSUE TITLE
[wish] adding a progress meter in every installation step?

### ISSUE THREAD

**Issue by FredBezies** [obrevenge/revenge_installer#6]
Hello.

I'm currently testing Revenge installer 0.8.2.

I noticed there is not a progress meter in % telling user how many is done. Could it be added to help user to know how much time is required until the end of every single task ? Thanks.

**Comment by spookykidmm** [comment]
The percent thing is possible but probably not the time remaining. Will be worked on for 0.86

**Comment by FredBezies** [comment]
Ok. Thanks for the info. Testing your last ISO related to other bugs I reported.

**Comment by spookykidmm** [comment]
Should be available in newest release

_Sent from my Samsung SAMSUNG-SM-G935A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by FredBezies** [comment]
Great!

**Comment by FredBezies** [comment]
Testing Zen Installer. There is a progression bar in every step. So, let's close this one :)
