### ISSUE TITLE
Open pacman.conf option at the end of installation process is not working.

### ISSUE THREAD

**Issue by FredBezies** [obrevenge/revenge_installer#7]
Hello.

Saw this in Revenge installer 0.8.2. After installation is finished, you propose to open pacman.conf. I choose this option and nothing happened.

What is broken?

**Comment by spookykidmm** [comment]
I realize what I did wrong, but that bit is part of the iso, so it will not be fixed until I spin an iso next month

**Comment by spookykidmm** [comment]
Let me know if it works this time around

**Comment by FredBezies** [comment]
Doesn't seem to work better :(

**Comment by spookykidmm** [comment]
Just curious, are you on a uefi system?

**Comment by FredBezies** [comment]
No. Bios. Every single test I made here was done in a VirtualBox machine with classical bios enabled.

**Comment by spookykidmm** [comment]
Will be fixed at the next ISO release

_Sent from my Samsung SAMSUNG-SM-G935A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by FredBezies** [comment]
Ok. Thanks for the info!

**Comment by FredBezies** [comment]
Fixed in Zen Installer 1.0. Next? :)
